// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH1oJi4NV8wJ3_l_a5Q2njAxR__qBLu-4',
    appId: '1:615230523314:web:8d9c61149a741d3f7d86ab',
    messagingSenderId: '615230523314',
    projectId: 'test-e6741',
    authDomain: 'test-e6741.firebaseapp.com',
    databaseURL: 'https://test-e6741-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-e6741.appspot.com',
    measurementId: 'G-9QV6QMDMRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKkv6YHgd4mvpF0BITOOblTCUcsAhaPFs',
    appId: '1:615230523314:android:23ae92789b8b0df97d86ab',
    messagingSenderId: '615230523314',
    projectId: 'test-e6741',
    databaseURL: 'https://test-e6741-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-e6741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpKyWkt0cnhUHPX8c9Nt7N_LvFTxO1v4',
    appId: '1:615230523314:ios:42c41db40bf4e71a7d86ab',
    messagingSenderId: '615230523314',
    projectId: 'test-e6741',
    databaseURL: 'https://test-e6741-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-e6741.appspot.com',
    iosBundleId: 'com.example.providerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpKyWkt0cnhUHPX8c9Nt7N_LvFTxO1v4',
    appId: '1:615230523314:ios:1df5af0756ca16a67d86ab',
    messagingSenderId: '615230523314',
    projectId: 'test-e6741',
    databaseURL: 'https://test-e6741-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-e6741.appspot.com',
    iosBundleId: 'com.example.providerProject.RunnerTests',
  );
}
